### ISSUE TITLE
List of rides

### ISSUE THREAD

**Issue by liebeckm** [liebeckm/capstone-project#1]
## Value Proposition

- As a user
- I want a list of rides
- in order to read them

## Description

![us_1](https://user-images.githubusercontent.com/123425806/227487502-2dfc3885-9df4-42ab-a92b-7134a36cadde.png)

## Acceptance criteria

- [x] Each ride on a different card
- [x] Each card has
    - [x] driver
    - [x] rating
    - [x] start and endpoint
    - [x] time and date
    - [x] free seats
    - [x] price
    
- [x] The list is scrollable
- [x] The title "landwaerts" is displayed above the rides list and is not fixed
- [x] The Heading "Übersicht – Alle Fahrten" should be fixed

## Tasks

- [x] Global Styles
- [x] add component/card
- [x] write test
- [x] Create db.js with rides
- [x] Add to App
