### ISSUE TITLE
choose how many seats you'd like to book

### ISSUE THREAD

**Issue by liebeckm** [liebeckm/capstone-project#11]
## Value Proposition

- As a user
- I want to choose how many seats I'd like to book
- in order to take only as much space as needed

## Description

![Image](https://user-images.githubusercontent.com/123425806/231422336-132b4539-1719-4cd6-8874-73486befea5d.png)

## Acceptance criteria

- [ ] add dropdown menu on details page

   
## Tasks

- [ ] Create component/Dropdown
- [ ] update page/details-page
- [ ] write test for Dropdown

**Comment by Kachev** [comment]
I think it's great👍🏼

**Comment by liebeckm** [comment]
@PReichetanz I added error message as well as counter for the price so it adapts for the amount of seats needed.
