### ISSUE TITLE
Detail page of ride

### ISSUE THREAD

**Issue by liebeckm** [liebeckm/capstone-project#2]
## Value Proposition

- As a user
- I want to get detailed information for each ride
- in order to decide wether to book it or not

## Description

![Image](https://user-images.githubusercontent.com/123425806/227512367-170614f0-0bff-4b0e-a1e7-eaeb10ffad3d.png)

## Acceptance criteria
- [ ] add "auswählen button" to overview page from user story 1

- build the detail page with the following criteria:
  - [ ] Driverpicture, -name, and -car are displayed on top
  - [ ] Two cards:
  -  [ ] The first card has overview of ride including
     -  [ ] driver
      - [ ] start and endpoint
      - [ ] time and date
      - [ ] free seats
      - [ ] price

- [ ] The Detailpage is scrollable
- [ ] The title "landwaerts" is displayed above the rides list but is not fixed
- [ ] The "ausgewählte Fahrt" heading is fixed
- [ ] There is a "zurück zu allen Fahrten"-button which leads to the overview page that has been built already

## Tasks

- [ ] Create feature branch
- [ ] update component/card
- [ ] add component/button
- [ ] add page pages/details
- [ ] write test for buttons
- [ ] Add to App

**Comment by louisweiser** [comment]
LGTM
