### ISSUE TITLE
"booking successful"-page

### ISSUE THREAD

**Issue by liebeckm** [liebeckm/capstone-project#3]
## Value Proposition

- As a user
- I want to get a booking confirmation
- in order to know that my booking was successful

## Description

![Image](https://user-images.githubusercontent.com/123425806/228641343-893bb6d6-5eba-4a5e-ab5b-93f13ba8635b.png)

## Acceptance criteria
- [x] add "buchen"-button on details page

- booking confirmation page:
- [x] The title "landwaerts" is displayed above and not fixed
- [x] below, there is a "Fahrt gebucht!"-message (not fixed)
- [x] page is scrollable
- [x] driver and car are listed below
- [x] One card with overview of ride including
    - [x] contact data (phone)
    - [x] price including note to pay with cash
    - [x] summary of booked ride
- "meine Fahrten"-page
- [x] add "Meine Fahrten" button to navbar, fixed
- [x] The title "landwaerts" is displayed above and not fixed
- [x] below, there is a "Meine Fahrten"-message and "Anstehende Fahrten:"(not fixed)
- shows card with overview of ride:
    - [x] contact data (phone)
    - [x] price including note to pay with cash
    - [x] summary of booked ride
    
## Tasks

- [x] Create feature branch
- [x] update component/card
- [x] add page pages/confirmation
- [x] add page pages/myrides
- [x] add fixed navbar with "Meine Fahrten" that links to pages/myrides
- [x] write test for "buchen"-button and for navbar
- [x] Add to App

**Comment by dennisbuchwald** [comment]
Very good user story, makes a lot of sense and I like it. 😊

**Comment by PReichetanz** [comment]
Nice work!

One question: If I've booked a ride and go back to the overview, do I have any option to see my bookings? This should be part of this story as well, because otherwise, I can "book" something, but it's gone as soon as I leave the page.

**Comment by liebeckm** [comment]
@PReichetanz  good point, normally would have done this into another US. My plan was to add a link to the nav bar with "my rides". Will add this asap!

**Comment by PReichetanz** [comment]
Nice work! Just one last question:
Shouldn't it also be possible to go from "Alle Fahrten" to "Meine Fahrten" with this new Link you have just added to the details and booking page? If so (i.e. if you are going to add the Link on the list page as well), you should add this screen to the description because something has changed on this page.
