### ISSUE TITLE
Search page

### ISSUE THREAD

**Issue by liebeckm** [liebeckm/capstone-project#6]
## Value Proposition

- As a user
- I want to search a ride
- in order to have an overview of offered rides

## Description

![Image](https://user-images.githubusercontent.com/123425806/229752085-ace4b41a-beb3-4938-a6a9-39e1f2ce6aa1.png)

## Acceptance criteria

- [ ] add "search button" that leads to filtered overview page 

- build filtered search form(?) with the following fields:
  - [ ] Departure
  - [ ] Drop-down
  - [ ] time
  - [ ] date
  - [ ] number of persons

- [ ] The title "landwaerts" is displayed above the rides
- [ ] The "Wohin soll es gehen" h2 is displayed below the title
- [ ] next to the "Meine Fahrten"-Link in the Navbar, there should be a "Search"-Link from now on as well

## Tasks

- [ ] Create feature branch
- [ ] create component/searchform
- [ ] update component/button
- [ ] add page pages/search
- [ ] add search Link to navbar
- [ ] write test for buttons, filter functions
- [ ] Add to App

**Comment by LuYujin9** [comment]
Looks great!  only the "Meine Fahrten"-Link.  Paul said that ,when the link is still not there, the link button should be in this Page.🥲

**Comment by liebeckm** [comment]
@LuYujin9 I implemented this link earlier in another user story so I guess it's fine then? ☺️

**Comment by manukao** [comment]
lgtm - though I am not completely sure if we shouldnt keep the user stories more flexible/general, especially the acceptance criteria. E.g. we should not specify that a "h2" is used etc.
