### ISSUE TITLE
Add ride page

### ISSUE THREAD

**Issue by liebeckm** [liebeckm/capstone-project#7]
## Value Proposition

- As a user
- I want to offer a ride
- in order to find passengers 

## Description

![Image](https://user-images.githubusercontent.com/123425806/228854808-63afbbd4-2d95-4a92-9982-a5ec62167207.png)

## Acceptance criteria

screen1:
- build form with the following fields:
  - [ ] Departure
  - [ ] Destination
  - [ ] Time and date
  - [ ] number of persons
  - [ ] Price
- [ ] add "veröffentlichen"-button that leads to confirmation page (screen 2); after clicking the button, the ride should also appear in "Meine Fahrten" (screen 3)
- [ ] next to the "Meine Fahrten"-Link and "Search"-Link there should be a "Fahrten anbieten"-Link from now on as well

screen 2:
- [ ] add card with confirmation message

screen 3:
- [ ] add card for newly offered ride
- [ ] make "Meine Fahrten" page scrollable
- [ ] make Headings "Anstehend" and "Deine Inserate" fixed

## Tasks

- [ ] Create feature branch
- [ ] create component/AddRideForm
- [ ] connect AddRideForm with local data storage
- [ ] update component/button
- [ ] update component/card and add new card to "Meine Fahrten" once the "veröffentlichen" button got clicked
- [ ] add page pages/add-ride
- [ ] - [ ] add page pages/add-ride-success
- [ ] add "Fahrt anbieten" Link to navbar
- [ ] write test for buttons, form, appearance of new ride in "Meine Fahrten"
- [ ] Add to App

**Comment by LuYujin9** [comment]
How do you think? When the new ride hat been added, lead to screen 3. the new one will be in the top. when not, then a error message shows in screen 2, or cancel screen 2 only show the message on top of the screen3?

**Comment by liebeckm** [comment]
@LuYujin9 Thank you, I tried to update my US according to your input

**Comment by alexWaligorski** [comment]
Hi Melissa, looks great!
- I would recommend to split the input for time and date, because these are two different pieces of information. Also, there are input types date and time which provide you with a UI element (date-picker, time-picker).
- Besides that I was wondering: Do you need the "Fahrt suchen" navigation link already? If no search is implemented, you should remove it from the nav from now.
- Maybe you can get rid of the error message. When you set all inputs to required, the browservalidation will throw an error and a message anyways.

Anyhow: 👍
