### ISSUE TITLE
edit offered rides

### ISSUE THREAD

**Issue by liebeckm** [liebeckm/capstone-project#9]
## Value Proposition

- As a user
- I want to edit my offered rides
- in order to make changes

## Description

![Image](https://user-images.githubusercontent.com/123425806/230356302-1e52bcba-dde6-4ee1-9893-aa932e8912be.png)

## Acceptance criteria
Screen 1:
- [ ] add "bearbeiten"-button on every offered ride on the "Meine Fahrten" page

Screen 2:
- [ ] The title "landwaerts" is displayed above and not fixed
- [ ] below, there is a "Fahrt bearbeiten"-Heading (not fixed)
- [ ] The Form has already filled-in the saved data
- [ ] This already saved data can be edited
- [ ] page is scrollable
- [ ] There are two buttons; "zurück" which leads to "Meine Fahrten"-Overview and "Aktualisieren" which saves the updated data
- [ ] Once clicked on "Aktualisieren", there is a message between the form and the links, saying "Deine Fahrt wurde aktualisiert"
    
## Tasks

- [ ] Create feature branch
- [ ] update component/card
- [ ] update component/form
- [ ] write test for "Aktualisieren"-button 
- [ ] Add to App
